<div class="jumbotron">
  <h2>一个用beego写的blog</h2>
  <p>一个采用beego框架写的简单的博客，包括了以下功能<br>
1.登录功能/session记录<br>
2.后台添加博文<br>
3.后台修改博文<br>
4.删除博文<br>
5.分类管理<br>
6.友情链接<br>
7.按月查看<br>
8.博客配置<br>
9.账号管理<br>
TODO<br>
1.替换编辑器为markdown编辑器<br>
2.继续丰富博客功能<br>
联系方式<br>
rockxsj#gmail.com
  </p>
</div>